/**
 * demo/scripts/build.mjs
 *
 * Two jobs:
 *
 * 1. Inline kalakar/kit/filters.svg into demo/index.html at the
 *    <!--KALAKAR_FILTERS--> marker.
 *
 *    WHY: CSS url(#id) only resolves against SVG filter defs in the SAME
 *    document. <img src="filters.svg"> and <use href="…"> both fail. The defs
 *    have to be inlined — by a build step, a server include, or a framework
 *    component. This is the smallest version of that.
 *
 * 2. Emit demo/standalone.html — a single self-contained file with all CSS
 *    and JS inlined.
 *
 *    WHY: browsers block EXTERNAL ES module fetches over file:// as a
 *    cross-origin request, so double-clicking index.html loads the CSS but
 *    silently skips motion.js — no reveals, no glass detection, no cursor.
 *    (Inline modules are fine; only external ones are blocked.) index.html
 *    stays the readable, canonical source for serving; standalone.html is the
 *    one you can just open.
 *
 * Both outputs are idempotent — re-running replaces the generated blocks.
 *
 * Run: node demo/scripts/build.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const DEMO = join(HERE, "..");
const KIT = join(DEMO, "..", "kalakar", "kit");

const HTML = join(DEMO, "index.html");
const STANDALONE = join(DEMO, "standalone.html");

const OPEN = "<!--KALAKAR_FILTERS-->";
const CLOSE = "<!--/KALAKAR_FILTERS-->";

/* ---------------------------------------------------------- 1. inline defs */
let html = readFileSync(HTML, "utf8");
const svg = readFileSync(join(KIT, "filters.svg"), "utf8")
  .replace(/<\?xml[^>]*\?>\s*/, "") // strip the XML decl — invalid mid-HTML
  .trim();

const block = `${OPEN}\n${svg}\n${CLOSE}`;
const start = html.indexOf(OPEN);
if (start === -1) {
  console.error(`marker ${OPEN} not found in index.html`);
  process.exit(1);
}
const closeAt = html.indexOf(CLOSE);
const end = closeAt === -1 ? start + OPEN.length : closeAt + CLOSE.length;

html = html.slice(0, start) + block + html.slice(end);
writeFileSync(HTML, html, "utf8");

const ids = [...svg.matchAll(/id="([^"]+)"/g)].map((m) => m[1]);
console.log(`index.html      inlined ${(svg.length / 1024).toFixed(1)} KB of filter defs`);
console.log(`                ids: ${ids.join(", ")}`);

/* ------------------------------------------------------- 2. standalone.html */
const css = {
  "../kalakar/kit/tokens.css": readFileSync(join(KIT, "tokens.css"), "utf8"),
  "../kalakar/kit/glass.css": readFileSync(join(KIT, "glass.css"), "utf8"),
  "demo.css": readFileSync(join(DEMO, "demo.css"), "utf8"),
};

let sa = html;

// stylesheets -> <style>
for (const [href, source] of Object.entries(css)) {
  const tag = new RegExp(`<link rel="stylesheet" href="${href.replace(/[./]/g, "\\$&")}">`);
  if (!tag.test(sa)) { console.error(`could not find <link> for ${href}`); process.exit(1); }
  sa = sa.replace(tag, `<style>/* ${href} */\n${source}\n</style>`);
}

// The grid SVG is referenced from demo.css by relative URL, which still
// resolves fine next to standalone.html — leave it alone.

// motion.js -> inline module. Strip the import and re-expose the two symbols
// the page uses; everything else in the module is already in scope once
// inlined.
const motion = readFileSync(join(KIT, "motion.js"), "utf8");
sa = sa.replace(
  /import \{ initKalakar, env \} from "\.\.\/kalakar\/kit\/motion\.js";/,
  `/* ---- inlined from kalakar/kit/motion.js ---- */\n${motion}\n/* ---- end kit ---- */`
);

sa = sa.replace(
  "<title>",
  "<!-- GENERATED by scripts/build.mjs — self-contained; edit index.html instead. -->\n<title>"
);

writeFileSync(STANDALONE, sa, "utf8");
console.log(`standalone.html ${(sa.length / 1024).toFixed(1)} KB, fully self-contained (open directly)`);
