/**
 * demo/scripts/gen-fonts.mjs
 *
 * Self-hosts the demo's webfonts — latin subset only — and writes
 * demo/assets/fonts/fonts.css.
 *
 * WHY (references/assets.md section 4): a Google Fonts <link> is a
 * render-blocking stylesheet on a third-party origin. It costs a DNS lookup, a
 * TLS handshake, and a round trip before the browser can even discover the
 * font files. Lighthouse measured it at ~2.0s of render-blocking on this page.
 * It is also a GDPR problem in the EU, because the CDN sees the visitor's IP.
 *
 * Self-hosting turns that into two same-origin requests the browser can
 * preload immediately. This script is what "self-host your fonts" actually
 * means in practice, and it is reusable on any project.
 *
 * Run: node demo/scripts/gen-fonts.mjs
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "assets", "fonts");
mkdirSync(OUT, { recursive: true });

// Google serves woff2 only to browser UAs; a default Node fetch gets ttf.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const SRC =
  "https://fonts.googleapis.com/css2" +
  "?family=Instrument+Serif:ital@0;1" +
  "&family=Inter:wght@300..500" +
  "&display=swap";

const css = await (await fetch(SRC, { headers: { "User-Agent": UA } })).text();

/* Keep only the `latin` blocks. Google ships 7+ subsets per family
   (cyrillic, greek, vietnamese, latin-ext…). Shipping all of them for an
   English page is 6 files of dead weight. Drop the rest; `unicode-range`
   means a visitor who somehow needs Cyrillic just falls back. */
const blocks = [];
const re = /\/\*\s*latin\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
let m;
while ((m = re.exec(css))) blocks.push(m[1]);

if (!blocks.length) {
  console.error("no latin @font-face blocks found — did the API response shape change?");
  process.exit(1);
}

const rules = [];
for (const block of blocks) {
  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
  const style = /font-style:\s*([^;]+);/.exec(block)?.[1].trim();
  const weight = /font-weight:\s*([^;]+);/.exec(block)?.[1].trim();
  const url = /src:\s*url\(([^)]+)\)/.exec(block)?.[1];
  const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1].trim();
  if (!family || !url) continue;

  const slug =
    family.toLowerCase().replace(/\s+/g, "-") +
    (style === "italic" ? "-italic" : "") +
    "-latin.woff2";

  const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
  writeFileSync(join(OUT, slug), buf);
  console.log(`  ${slug.padEnd(34)} ${(buf.length / 1024).toFixed(1)} KB`);

  /* Metric overrides keep the fallback the same height as the webfont, so the
     swap does not reflow. This is what drives CLS to 0 — see assets.md.
     Values are per-family; regenerate with `fontaine` or `capsize` if you
     change families. */
  const overrides =
    family === "Inter"
      ? "  ascent-override: 96.88%;\n  descent-override: 24.12%;\n  line-gap-override: 0%;\n"
      : "  ascent-override: 91%;\n  descent-override: 26%;\n  line-gap-override: 0%;\n";

  rules.push(
    `@font-face {\n` +
    `  font-family: '${family}';\n` +
    `  font-style: ${style};\n` +
    `  font-weight: ${weight};\n` +
    `  font-display: swap;\n` +
    `  src: url('./${slug}') format('woff2');\n` +
    overrides +
    (range ? `  unicode-range: ${range};\n` : "") +
    `}`
  );
}

writeFileSync(
  join(OUT, "fonts.css"),
  `/* GENERATED by demo/scripts/gen-fonts.mjs — do not hand-edit.\n` +
  `   Latin subset only, self-hosted, with metric overrides so the fallback\n` +
  `   swap does not shift layout. See references/assets.md section 4. */\n\n` +
  rules.join("\n\n") + "\n",
  "utf8"
);

console.log(`\nwrote assets/fonts/fonts.css  (${rules.length} faces)`);
