/**
 * kalakar/kit/gen-filters.mjs
 *
 * Generates kit/filters.svg — the SVG filter defs the kit depends on:
 *   #kalakar-grain        film grain (feTurbulence, desaturated)
 *   #kalakar-lens         refraction via feDisplacementMap  (Tier 2 glass)
 *   #kalakar-lens-chroma  refraction + chromatic aberration
 *   #kalakar-lens-strong  heavier refraction for large panels
 *
 * WHY A GENERATOR: feDisplacementMap needs a *displacement map image* — an
 * image where the R channel encodes x-offset and G encodes y-offset, with
 * 128 (mid-gray) meaning "no displacement". We build that map as an inner
 * SVG and inline it as a percent-encoded data URI. Hand-writing the encoding
 * is error-prone; generating it is not.
 *
 * The map: neutral #808080 base, red gradient across X, green gradient down Y,
 * then an inner rounded rect painted back to #808080 so the CENTRE does not
 * displace and only a rim-width band bends. That is the lens.
 *
 * Usage:  node kalakar/kit/gen-filters.mjs
 * Output: kalakar/kit/filters.svg
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));

/**
 * Build the displacement-map SVG source.
 * @param {number} w      map width in px
 * @param {number} h      map height in px
 * @param {number} rim    width of the refracting band at the edge
 * @param {number} radius corner radius of the flat centre
 */
function displacementMap(w, h, rim, radius) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}">
<defs>
<linearGradient id="rx" x1="0" y1="0" x2="1" y2="0">
<stop offset="0%" stop-color="#000000"/><stop offset="100%" stop-color="#FF0000"/>
</linearGradient>
<linearGradient id="gy" x1="0" y1="0" x2="0" y2="1">
<stop offset="0%" stop-color="#000000"/><stop offset="100%" stop-color="#00FF00"/>
</linearGradient>
</defs>
<rect width="${w}" height="${h}" fill="#808080"/>
<rect width="${w}" height="${h}" fill="url(#rx)" style="mix-blend-mode:screen"/>
<rect width="${w}" height="${h}" fill="url(#gy)" style="mix-blend-mode:screen"/>
<rect x="${rim}" y="${rim}" width="${w - rim * 2}" height="${h - rim * 2}" rx="${radius}" fill="#808080"/>
</svg>`;
}

/** Percent-encode so the SVG survives as an href attribute value. */
function dataUri(svg) {
  const compact = svg.replace(/\n/g, "").replace(/>\s+</g, "><").trim();
  return "data:image/svg+xml," + encodeURIComponent(compact);
}

const MAP_STD = dataUri(displacementMap(320, 220, 18, 30));
const MAP_BIG = dataUri(displacementMap(600, 400, 30, 44));

const out = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  kalakar/kit/filters.svg — GENERATED by gen-filters.mjs. Do not hand-edit.

  Inline this into the document (not <img src>, not <use>): SVG filters are
  only referenceable by CSS url(#id) when the <svg> lives in the same DOM.
  Keep it hidden and aria-hidden. Width/height 0 + position:absolute so it
  never affects layout.
-->
<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0"
     style="position:absolute;width:0;height:0;overflow:hidden" aria-hidden="true" focusable="false">
  <defs>

    <!-- ================================================================
         GRAIN — fractal noise, desaturated. Drive at 3-8% opacity with
         mix-blend-mode: overlay. baseFrequency higher = finer grain.
         ================================================================ -->
    <filter id="kalakar-grain" x="0%" y="0%" width="100%" height="100%">
      <feTurbulence type="fractalNoise" baseFrequency="0.85" numOctaves="3" stitchTiles="stitch" result="n"/>
      <feColorMatrix in="n" type="saturate" values="0"/>
    </filter>

    <!-- ================================================================
         LENS — Tier 2 liquid glass refraction.
         Apply with:  backdrop-filter: url(#kalakar-lens) blur(6px) saturate(180%);
         Chromium only today; kit/motion.js feature-detects and adds
         .has-refraction to <html>. Tier 1 (blur+saturate) is the baseline.

         scale = refraction strength. 20 subtle / 44 clearly glass / 90 funhouse.
         ================================================================ -->
    <filter id="kalakar-lens" x="0%" y="0%" width="100%" height="100%"
            color-interpolation-filters="sRGB">
      <feImage href="${MAP_STD}" result="map" preserveAspectRatio="none"/>
      <feGaussianBlur in="map" stdDeviation="6" result="softmap"/>
      <feDisplacementMap in="SourceGraphic" in2="softmap" scale="42"
                         xChannelSelector="R" yChannelSelector="G"/>
    </filter>

    <!-- Larger panels: wider rim, more scale. -->
    <filter id="kalakar-lens-strong" x="0%" y="0%" width="100%" height="100%"
            color-interpolation-filters="sRGB">
      <feImage href="${MAP_BIG}" result="map" preserveAspectRatio="none"/>
      <feGaussianBlur in="map" stdDeviation="9" result="softmap"/>
      <feDisplacementMap in="SourceGraphic" in2="softmap" scale="68"
                         xChannelSelector="R" yChannelSelector="G"/>
    </filter>

    <!-- ================================================================
         LENS + CHROMATIC ABERRATION — real lenses split wavelengths at the
         rim. Displace three times at slightly different scales, keep one
         channel from each, screen them back together.
         Keep the R/B spread under ~10 or it stops reading as glass.
         ================================================================ -->
    <filter id="kalakar-lens-chroma" x="0%" y="0%" width="100%" height="100%"
            color-interpolation-filters="sRGB">
      <feImage href="${MAP_STD}" result="map" preserveAspectRatio="none"/>
      <feGaussianBlur in="map" stdDeviation="6" result="m"/>

      <feDisplacementMap in="SourceGraphic" in2="m" scale="47" xChannelSelector="R" yChannelSelector="G" result="dR"/>
      <feDisplacementMap in="SourceGraphic" in2="m" scale="42" xChannelSelector="R" yChannelSelector="G" result="dG"/>
      <feDisplacementMap in="SourceGraphic" in2="m" scale="37" xChannelSelector="R" yChannelSelector="G" result="dB"/>

      <feColorMatrix in="dR" type="matrix" result="rOnly"
        values="1 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 1 0"/>
      <feColorMatrix in="dG" type="matrix" result="gOnly"
        values="0 0 0 0 0  0 1 0 0 0  0 0 0 0 0  0 0 0 1 0"/>
      <feColorMatrix in="dB" type="matrix" result="bOnly"
        values="0 0 0 0 0  0 0 0 0 0  0 0 1 0 0  0 0 0 1 0"/>

      <feBlend in="rOnly" in2="gOnly" mode="screen" result="rg"/>
      <feBlend in="rg" in2="bOnly" mode="screen"/>
    </filter>

  </defs>
</svg>
`;

mkdirSync(HERE, { recursive: true });
const dest = join(HERE, "filters.svg");
writeFileSync(dest, out, "utf8");
console.log(`wrote ${dest}  (${(out.length / 1024).toFixed(1)} KB)`);
